# imu_filter_madgwick:
#     ros__parameters:
#         fixed_frame: "base_link"
#         use_mag: true 
#         publish_tf: false
#         world_frame: "enu"
#         orientation_stddev: 0.05
#         yaw_offset: 0.0
        
#         stateless: false
#         reverse_tf: false
#         constant_dt: 0.0
#         publish_debug_topics: false
#         gain: 0.1
#         zeta: 0.0
#         mag_bias_x: 0.0
#         mag_bias_y: 0.0
#         mag_bias_z: 0.0


# MANUFACTURER:
imu_filter_madgwick:
    ros__parameters:
        fixed_frame: "base_link"
        use_mag: false
        publish_tf: false
        world_frame: "enu"
        orientation_stddev: 0.05
        gain: 0.1
